# Generated by Django 4.2.6 on 2023-11-13 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fireapp', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='threshold',
        ),
    ]
