# Generated by Django 4.2.6 on 2023-11-14 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fireapp', '0005_chart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chart',
        ),
    ]
