# Generated by Django 4.2.6 on 2023-11-28 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fireapp', '0006_delete_chart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='id',
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sensor_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
