# Generated by Django 4.2.6 on 2023-12-05 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fireapp', '0007_remove_sensor_id_alter_sensor_sensor_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=25, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='static/img/userProfile/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
